### ISSUE TITLE
Failing to deserialize from `serde_json::Value`

### ISSUE THREAD

**Issue by morph-dev** [sigp/enr#62]
The NodeId can't deserialize from `serde_json::Value` object.

Here is a simple test (unwrap crashes because deserialization returns None)
``` 
#[cfg(feature = "serde")]
#[test]
fn test_serde_value() {
    let node = NodeId::random();
    let value = serde_json::to_value(&node).unwrap();
    assert_eq!(node, serde_json::from_value::<NodeId>(value).unwrap());
}
```

One way to fix it is to change `deserialize` function to:

```
let raw: String = serde::Deserialize::deserialize(deserializer)?;
let src = raw.strip_prefix("0x").unwrap_or(&raw);
hex::FromHex::from_hex(src).map_err(serde::de::Error::custom)

```
but this is not optimal in other cases.

If you are fine with this fix, I can create a PR.

**Comment by morph-dev** [comment]
Might be worth noting that maybe the best way is to try the current implementation (deserializing to byte slice) and only try my fix if that one fails.

**Comment by divagant-martian** [comment]
thanks for the issue @morph-dev. I don't fully get what's going on, could you explain from your understanding why this serialization is failing? A bit surprising. 

Regardless, we definitely care first about correctness than performance so I would be on board with this change. But being honest, I first need to understand the root of the issue for a proper review

**Comment by morph-dev** [comment]
My understanding is that deserializing into byte slice works fine for [`serde_json::from_slice`](https://docs.rs/serde_json/1.0.107/serde_json/fn.from_slice.html) and [`serde_json::from_str`](https://docs.rs/serde_json/1.0.107/serde_json/fn.from_str.html) because they accept borrowed parameter.

However, [`serde_json::from_value`](https://docs.rs/serde_json/1.0.107/serde_json/fn.from_value.html) moves the `Value` object, so we can't deserialize it into byte slice, but deserializing it into `String` works fine.

I believe that previous implementation, that used [`serde-hex`](https://docs.rs/serde-hex) crate had the same issue. There is forked version, the [`stremio-serde-hex`](https://docs.rs/stremio-serde-hex/latest), which implemented the special `serde::de::Visitor` ([link](https://github.com/Stremio/serde-hex/blob/edd3bd42d315677e87f633f962371ebc925ba52f/src/lib.rs#L144)) to deal with it. 

I will create a PR with suggested changes.

**Comment by morph-dev** [comment]
Also, we ([Trin](https://github.com/ethereum/trin)) would like to remove our own implementation of [`NodeId`](https://github.com/ethereum/trin/blob/4fd5f7bdcff4dad58fff7d86c831e8e9768c8a2f/ethportal-api/src/types/node_id.rs) and use this one instead (which we already do in many places).

So we would appreciate if new release could be published soon after this is fixed.

**Comment by weipin** [comment]
( This is something rushed; please double-check and verify. )

The problem is that the types don't match. The current `NodeId` deserializing
code requires a `str`, but what `Value` can provide is a `String`.

I am afraid we cannot find a way to force `serde_json::from_value` to give us a
value with a lifetime such as `str`, because the trait involves is `DeserializeOwned`
, not `Deserialize`.

The good news is that we don't need to return the "string" itself, but to find a way
to handle the two possible input types (borrowed and owned).

I figure that `Cow<str>` could be used here, and the code below seems to work.
This way, we might be able to preserve the performance (avoiding string copying)
and at the same time support `from_value`.

"import" `Cow`:
```
/// Serialize with the 0x prefix.
#[cfg(feature = "serde")]
mod serde_hex_prfx {
    use std::borrow::Cow;
    ...
```

Main code:
```
    {
        let raw: Cow<str> = serde::Deserialize::deserialize(deserializer)?;
        let src = raw.strip_prefix("0x").unwrap_or(&raw);
        hex::FromHex::from_hex(src).map_err(serde::de::Error::custom)
    } 
```

**Comment by divagant-martian** [comment]
This was a good lead. It needs some work because since there is no explicit lifetime serde produces an owned string everytime. I've fixed the pr and will merge soon. A release is unlikely for the next week though

**Comment by morph-dev** [comment]
Thanks for fixing it.

Can you maybe ping this issue once new released is pushed. Thanks
